name: Homolog

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    
jobs:
  build:
    runs-on: [self-hosted, homolog]
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create back-end env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_PORT: ${{secrets.PORT_HOMOLOG}}
          envkey_POSTGRES_USERNAME: ${{secrets.POSTGRES_USERNAME_HOMOLOG}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD_HOMOLOG}}
          envkey_POSTGRES_DATABASE: ${{secrets.POSTGRES_DATABASE_HOMOLOG}}
          envkey_POSTGRES_HOST: ${{secrets.POSTGRES_HOST_HOMOLOG}}
          envkey_POSTGRES_PORT: ${{secrets.POSTGRES_PORT_HOMOLOG}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL_HOMOLOG}}
          envkey_DRFINANCAS_API_KEY: ${{secrets.DRFINANCAS_API_KEY_HOMOLOG}}
          envkey_DRFINANCAS_API_URL: ${{secrets.DRFINANCAS_API_URL_HOMOLOG}}
          envkey_EXPECTED_API_KEY: ${{secrets.EXPECTED_API_KEY_HOMOLOG}}
          directory: api
          file_name: .env
          fail_on_empty: true
          
      - name: Run docker compose down
        run: docker compose down -v

      - name: Run docker compose up
        run: docker compose up --build -d